# spring:
#   application:
#     name: finflow-gateway-service

#   cloud:
#     gateway:
#       mvc:
#         routes:

#           - id: auth-service
#             uri: lb://FINFLOW-AUTH-SERVICE
#             predicates:
#               - Path=/gateway/auth/**
#             filters:
#               - StripPrefix=1

#           - id: application-service
#             uri: lb://FINFLOW-APPLICATION-SERVICE
#             predicates:
#               - Path=/gateway/applications/**
#             filters:
#               - StripPrefix=1

#           - id: document-service
#             uri: lb://FINFLOW-DOCUMENT-SERVICE
#             predicates:
#               - Path=/gateway/documents/**
#             filters:
#               - StripPrefix=1

#           - id: admin-service
#             uri: lb://FINFLOW-ADMIN-SERVICE
#             predicates:
#               - Path=/gateway/admin/**
#             filters:
#               - StripPrefix=1

# server:
#   port: 8080

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka

# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"









spring:
  cloud:
    gateway:
      server:
        webmvc:

          routes:

            - id: auth-service
              uri: lb://FINFLOW-AUTH-SERVICE
              predicates:
                - Path=/auth/**

            - id: application-service
              uri: lb://FINFLOW-APPLICATION-SERVICE
              predicates:
                - Path=/application/**
              filters:
                - StripPrefix=0
              # filters:
              #   - PreserveHostHeader
              #   - AddRequestHeader=Authorization, #{request.headers.Authorization}

            - id: admin-service
              uri: lb://FINFLOW-ADMIN-SERVICE
              predicates:
                - Path=/admin/**

            - id: document-service
              uri: lb://FINFLOW-DOCUMENT-SERVICE
              predicates:
                - Path=/documents/**

jwt:
  secret: finflowSecretKeyFinflowSecretKey
  expiration: 86400000

logging:
  level:
    org.springframework.cloud.gateway: TRACE
