server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/gateway/auth/**
          filters:
            - StripPrefix=1

        - id: application-service
          uri: lb://application-service
          predicates:
            - Path=/gateway/applications/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter

        - id: document-service
          uri: lb://document-service
          predicates:
            - Path=/gateway/documents/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter

        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/gateway/admin/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

jwt:
  secret: finflow-super-secret-jwt-key-must-be-at-least-256-bits-long-for-hs256

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
